# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: (Prof) Dr. Kusum Deep
email: kusumfma@iitr.ernet.in
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/testingsite" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll


# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
#minimal_mistakes_skin: "neon"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  #- jekyll-remote-theme 

defaults:
  #pages
  - scope:
      path: ""
      type: pages
    values:
        layout: single
        author_profile: true

author:
  name: "Kusum Deep"
  avatar: "/assets/images/mom.jpg"
  bio: "Professor, <br>IIT Roorkee."
  location: "Roorkee"
  email: "kusumfma@iitr.ernet.in"   
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.co.in/citations?user=ByQN_c0AAAAJ&hl=en"
    - label: "SCRS"
      icon: "fas fa-fw fa-link"
      url: "http://scrs.in/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kusum-kusumdeep-18927463/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/kusumdeep"

include: 
  - _pages
  - _data
  - _includes
#remote_theme: benbalter/retlab
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
